# Домашнее задание "Линейная алгебра. Матрицы".

In [4]:
import numpy as np

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9


In [9]:
A1 = np.array([i for i in range(1, 10)]).reshape((3, 3))
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

 - Прибавьте к ней матрицу с единицами на диагонале

In [10]:
A2 = A1 + np.eye(3)
A2

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

 - Умножьте полученную матрицу на вектор (1, 2, 3)


In [11]:
A3 = A2 @ np.array([1, 2, 3])
A3

array([15., 34., 53.])

 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы

In [12]:
A4 = A2.T
A4

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

 - Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [13]:
A5 = np.linalg.inv(A2)
A5

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01,  5.44009282e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [14]:
m = np.array([[2, 2],
              [1, 3]])


In [39]:
str(vec)

'[[-0.89442719 -0.70710678]\n [ 0.4472136  -0.70710678]]'

In [41]:
zn, vec = np.linalg.eig(m)
print(f'Собственные значения: {zn}')
print(f'Собственные векторы: {vec}')

Собственные значения: [1. 4.]
Собственные векторы: [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [70]:
my_m = np.array(
    [
        [0.5, 0.75,],
        [1, -0.5]

    ]
)
my_m

array([[ 0.5 ,  0.75],
       [ 1.  , -0.5 ]])

In [71]:
np.linalg.det(my_m)

-1.0