# Предсказываем стоимость мед страховки



## Загужаем необходимые библиотеки

In [20]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np


## Загружаем данные

Собраны данные:
- age: возраст
- sex: пол
- bmi: индекс массы тела
- children: количество детей, охваченных медицинским страхованием / количество иждивенцев
- smoker: курение
- region: регион (northeast, southeast, southwest, northwest).
- charges: индивидуальные медицинские расходы (его и хотим предсказать)

In [2]:
# Загрузите данные из файла insurance.csv в переменную df
df = pd.read_csv('insurance.csv')

In [3]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## Смотрим статистику, что нет пропусков и отсуствующих значений

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [5]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

## Преобразуем строковые данные

In [6]:
# Заменяем пол и курение на числа
df['sex']=df['sex'].map({'male':1, 'female':0})
df['smoker']=df['smoker'].map({'yes':1,'no':0})

In [7]:
df.head()

age  sex     bmi  children  smoker     region      charges
0   19    0  27.900         0       1  southwest  16884.92400
1   18    1  33.770         1       0  southeast   1725.55230
2   28    1  33.000         3       0  southeast   4449.46200
3   33    1  22.705         0       0  northwest  21984.47061
4   32    1  28.880         0       0  northwest   3866.85520

In [8]:
# Заменяем регион на набор отдельных колонок (is_southwest, is_southeast и тп)
df = pd.get_dummies(df, columns=['region'])
df.head()

age  sex     bmi  children  smoker      charges  region_northeast  \
0   19    0  27.900         0       1  16884.92400                 0   
1   18    1  33.770         1       0   1725.55230                 0   
2   28    1  33.000         3       0   4449.46200                 0   
3   33    1  22.705         0       0  21984.47061                 0   
4   32    1  28.880         0       0   3866.85520                 0   

   region_northwest  region_southeast  region_southwest  
0                 0                 0                 1  
1                 0                 1                 0  
2                 0                 1                 0  
3                 1                 0                 0  
4                 1                 0                 0

## Формируем признаки и целевую переменную

In [ ]:
## Сформируйте признаки и целевую переменную

In [9]:
X, y = df.drop('charges', axis=1), df['charges']

## Разделяем данные на выборку для обучения/проверки

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Создаем и обучаем модель линейной регресии

In [14]:
# Создайте и обучите модель
lr = LinearRegression()
lr.fit(X, y)
lr.coef_

array([  256.85635254,  -131.3143594 ,   339.19345361,   475.50054515,
       23848.53454191,   587.00923503,   234.0453356 ,  -448.01281436,
        -373.04175627])

## Получаем предсказание и оцениваем качество

In [15]:
# Получите предсказание
lr.predict(X_test)

array([15102.13054843,  6019.07724659,  1610.75150127,  5627.71154995,
       14746.7427172 ,   -95.96875592, 17859.13098675, 12351.32368566,
        2834.59247579,  9528.43626647,  7447.08139941,  7503.27636554,
       10546.75391069, 13636.90420536,  6695.42273543,  9756.36772522,
       11111.08502593, 13940.60024839, 34189.57643384, 12820.01257586,
       36052.94833   ,  9952.90475899, 11431.24413165, 30624.9137832 ,
        6331.09280229, 39345.73378657,  8831.7085101 , 10860.26749492,
       33120.6527831 , 10023.62691025,  9974.64383302, 11222.12348433,
        8364.64359917,  7188.46955632,  5776.00825333, 11713.24965422,
       11474.74110792,  2604.46335851, 11413.27778615,  9390.47682853,
        5719.01600198,  3154.3135483 , 16241.60521545, 31796.42041052,
        3044.57940674,  1189.42673904,  5292.90229375, 15025.43712603,
       35111.83797726, 13652.23328826,  6512.94830456,  7629.78159248,
        4503.41015199,  6062.93582201,  4766.14955465, 13277.04962668,
      

In [ ]:
# Оцените качество, при помощи метода mean_squared_error для тестовой выборки

In [21]:
np.sqrt(mean_squared_error(y_test, lr.predict(X_test)))

6316.3851111329805

## Делаем предсказание для одного человека

In [22]:
# Заполняем данные по конкретному человеку
data = [{
    "age": 20,
    "sex": 1,
    "bmi": 30,
    "children": 2,
    "smoker": 1,
    "region_northeast": 0,
    "region_northwest": 0,
    "region_southeast": 1,
    "region_southwest": 0
}]

In [23]:
df_person = pd.DataFrame(data)
df_person.head()

age  sex  bmi  children  smoker  region_northeast  region_northwest  \
0   20    1   30         2       1                 0                 0   

   region_southeast  region_southwest  
0                 1                 0

In [24]:
lr.predict(df_person)

array([27007.59130633])

# Задание со звездочкой

In [25]:
df_cash = pd.read_csv('cash.csv', sep=',', decimal=',')
df_cash.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Месяц   12 non-null     int64  
 1   m-2     10 non-null     float64
 2   m-1     11 non-null     float64
 3   m       12 non-null     float64
 4   next    11 non-null     float64
dtypes: float64(4), int64(1)
memory usage: 608.0 bytes


In [28]:
# Заполняем пропуски

df_cash['m-2'].fillna(df_cash['m-2'].median(), inplace=True)
df_cash['m-1'].fillna(df_cash['m-1'].median(), inplace=True)
df_cash['next'].fillna(df_cash['next'].mean(), inplace=True)
df_cash.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Месяц   12 non-null     int64  
 1   m-2     12 non-null     float64
 2   m-1     12 non-null     float64
 3   m       12 non-null     float64
 4   next    12 non-null     float64
dtypes: float64(4), int64(1)
memory usage: 608.0 bytes


In [31]:
# Делим выборку
X = df_cash[['m-2', 'm-1', 'm']]
y = df_cash['next']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [32]:
# Обучаем модель
lr_cash = LinearRegression()
lr_cash.fit(X_train, y_train)
lr_cash.coef_

array([ 0.37013562, -0.31659941, -0.14893355])

In [36]:
# Оценка качества
pd.DataFrame([y_test.values, lr_cash.predict(X_test)]).T

0             1
0  63063.68  28356.998731
1  40635.57  22759.694076
2  34915.16  30403.417670
3  64368.78  51351.246204

In [38]:
np.sqrt(mean_squared_error(y_test, lr_cash.predict(X_test)))

20699.714187379064