In [1]:
import numpy as np

# Двумерное ядро фильтра
kernel = np.array([[1, 2, 1],
                   [2, 4, 2],
                   [1, 2, 1]])

# Сингулярное разложение
U, S, V = np.linalg.svd(kernel)

# Проверка сепарабельности
print("Сингулярные значения:", S)
if np.sum(S > 1e-10) == 1:
    print("Фильтр сепарабельный")
else:
    print("Фильтр не сепарабельный")

Сингулярные значения: [6.00000000e+00 5.60898698e-16 3.88443959e-49]
Фильтр сепарабельный


In [2]:
S

array([6.00000000e+00, 5.60898698e-16, 3.88443959e-49])

In [3]:
np.sum(S)

6.000000000000002

In [4]:
S > 1e-10

array([ True, False, False])

In [5]:
import numpy as np

# Двумерное ядро фильтра
kernel = np.array([[1, 2, 1],
                   [2, 4, 2],
                   [1, 2, 1]])

# Применяем SVD
U, S, Vt = np.linalg.svd(kernel)

# Первое сингулярное значение
s1 = S[0]

# Соответствующие векторы
u1 = U[:, 0]  # Первый столбец матрицы U
v1 = Vt[0, :]  # Первый строка матрицы V^T

# Одномерные фильтры
horizontal_filter = np.sqrt(s1) * v1
vertical_filter = np.sqrt(s1) * u1

print("Горизонтальный фильтр:", horizontal_filter)
print("Вертикальный фильтр:", vertical_filter)

# Восстановленный фильтр
reconstructed_kernel = np.outer(vertical_filter, horizontal_filter)
print("Восстановленный фильтр:\n", reconstructed_kernel)


Горизонтальный фильтр: [-1. -2. -1.]
Вертикальный фильтр: [-1. -2. -1.]
Восстановленный фильтр:
 [[1. 2. 1.]
 [2. 4. 2.]
 [1. 2. 1.]]


In [6]:
horizontal_filter @ vertical_filter

6.0